services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - devsync-network
networks:
  devsync-network:
    external: true
    driver: bridge